"""
PDF Report Generator for MyNet scan results.

Generates professional PDF reports with:
- Executive summary
- Findings by severity
- Module-specific details
- Recommendations
"""

from datetime import datetime
from typing import Dict, Any, List
import io

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, Image, HRFlowable
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


class PDFReportGenerator:
    """Generates professional PDF reports from scan results."""

    def __init__(self):
        if not REPORTLAB_AVAILABLE:
            raise ImportError("reportlab is required for PDF generation. Install with: pip install reportlab")

        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

        # Color scheme
        self.colors = {
            "primary": colors.HexColor("#1a73e8"),
            "danger": colors.HexColor("#dc3545"),
            "warning": colors.HexColor("#ffc107"),
            "success": colors.HexColor("#28a745"),
            "info": colors.HexColor("#17a2b8"),
            "dark": colors.HexColor("#343a40"),
            "light": colors.HexColor("#f8f9fa"),
            "muted": colors.HexColor("#6c757d"),
        }

    def _setup_custom_styles(self):
        """Setup custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='MyNetTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor("#1a73e8"),
            alignment=TA_CENTER,
        ))

        self.styles.add(ParagraphStyle(
            name='MyNetSubtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.gray,
            alignment=TA_CENTER,
            spaceAfter=20,
        ))

        self.styles.add(ParagraphStyle(
            name='MyNetSectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor("#1a73e8"),
        ))

        self.styles.add(ParagraphStyle(
            name='MyNetSubSection',
            parent=self.styles['Heading3'],
            fontSize=12,
            spaceBefore=15,
            spaceAfter=8,
            textColor=colors.HexColor("#343a40"),
        ))

        self.styles.add(ParagraphStyle(
            name='MyNetFinding',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceBefore=5,
            spaceAfter=5,
            leftIndent=20,
        ))

    def generate(self, results: Dict[str, Any], output_path: str, **kwargs):
        """Generate PDF report from scan results."""
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50,
        )

        story = []

        # Title page
        story.extend(self._build_title_page(results, kwargs))

        # Executive summary
        story.extend(self._build_executive_summary(results))

        # Findings summary
        story.extend(self._build_findings_summary(results))

        # Detailed findings by module
        story.extend(self._build_detailed_findings(results))

        # Build PDF
        doc.build(story)

    def _build_title_page(self, results: Dict[str, Any], kwargs: dict) -> list:
        """Build the title page."""
        elements = []

        elements.append(Spacer(1, 2 * inch))

        # Title
        elements.append(Paragraph("Security Scan Report", self.styles['MyNetTitle']))

        # Target info
        targets = list(results.keys())
        if targets:
            target_str = targets[0] if len(targets) == 1 else f"{len(targets)} targets"
            elements.append(Paragraph(f"Target: {target_str}", self.styles['MyNetSubtitle']))

        # Date
        report_date = datetime.now().strftime("%B %d, %Y at %H:%M")
        elements.append(Paragraph(f"Generated: {report_date}", self.styles['MyNetSubtitle']))

        elements.append(Spacer(1, inch))

        # Horizontal line
        elements.append(HRFlowable(
            width="80%",
            thickness=2,
            color=self.colors["primary"],
            spaceBefore=20,
            spaceAfter=20,
        ))

        elements.append(Spacer(1, 0.5 * inch))

        # Tool branding
        elements.append(Paragraph("Generated by MyNet Scanner", self.styles['MyNetSubtitle']))

        elements.append(PageBreak())

        return elements

    def _build_executive_summary(self, results: Dict[str, Any]) -> list:
        """Build executive summary section."""
        elements = []

        elements.append(Paragraph("Executive Summary", self.styles['MyNetSectionHeader']))

        # Calculate statistics
        stats = self._calculate_stats(results)

        # Summary paragraph
        summary_text = f"""
        This security assessment was conducted on <b>{stats['total_targets']}</b> target(s) 
        using <b>{stats['modules_run']}</b> scanning modules. The scan identified 
        <b>{stats['total_findings']}</b> finding(s), including 
        <font color="red"><b>{stats['high_severity']}</b> high severity</font>, 
        <font color="orange"><b>{stats['medium_severity']}</b> medium severity</font>, and 
        <b>{stats['low_severity']}</b> low severity issue(s).
        """
        elements.append(Paragraph(summary_text, self.styles['Normal']))
        elements.append(Spacer(1, 20))

        # Statistics table
        stats_data = [
            ["Metric", "Value"],
            ["Targets Scanned", str(stats['total_targets'])],
            ["Modules Executed", str(stats['modules_run'])],
            ["Total Findings", str(stats['total_findings'])],
            ["High Severity", str(stats['high_severity'])],
            ["Medium Severity", str(stats['medium_severity'])],
            ["Low Severity", str(stats['low_severity'])],
        ]

        stats_table = Table(stats_data, colWidths=[3 * inch, 2 * inch])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), self.colors["primary"]),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), self.colors["light"]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ]))
        elements.append(stats_table)
        elements.append(Spacer(1, 30))

        return elements

    def _build_findings_summary(self, results: Dict[str, Any]) -> list:
        """Build findings summary section."""
        elements = []

        elements.append(Paragraph("Findings Summary", self.styles['MyNetSectionHeader']))

        findings = self._extract_all_findings(results)

        if not findings:
            elements.append(Paragraph(
                "No security vulnerabilities were identified during this scan.",
                self.styles['Normal']
            ))
            elements.append(Spacer(1, 20))
            return elements

        # Group by severity
        high_findings = [f for f in findings if f['severity'] == 'high']
        medium_findings = [f for f in findings if f['severity'] == 'medium']
        low_findings = [f for f in findings if f['severity'] == 'low']

        # High severity
        if high_findings:
            elements.append(Paragraph(
                f"🔴 High Severity ({len(high_findings)})",
                self.styles['MyNetSubSection']
            ))
            for f in high_findings[:10]:
                elements.append(Paragraph(
                    f"• <b>{f['module']}</b>: {f['description']}",
                    self.styles['MyNetFinding']
                ))
            elements.append(Spacer(1, 10))

        # Medium severity
        if medium_findings:
            elements.append(Paragraph(
                f"🟠 Medium Severity ({len(medium_findings)})",
                self.styles['MyNetSubSection']
            ))
            for f in medium_findings[:10]:
                elements.append(Paragraph(
                    f"• <b>{f['module']}</b>: {f['description']}",
                    self.styles['MyNetFinding']
                ))
            elements.append(Spacer(1, 10))

        # Low severity
        if low_findings:
            elements.append(Paragraph(
                f"🟡 Low/Info ({len(low_findings)})",
                self.styles['MyNetSubSection']
            ))
            for f in low_findings[:5]:
                elements.append(Paragraph(
                    f"• <b>{f['module']}</b>: {f['description']}",
                    self.styles['MyNetFinding']
                ))

        elements.append(PageBreak())

        return elements

    def _build_detailed_findings(self, results: Dict[str, Any]) -> list:
        """Build detailed findings by target/module."""
        elements = []

        elements.append(Paragraph("Detailed Findings", self.styles['MyNetSectionHeader']))

        for host, data in results.items():
            elements.append(Paragraph(f"Target: {host}", self.styles['MyNetSubSection']))

            scans = data.get("scans", {})

            for module_name, module_data in scans.items():
                if not module_data or isinstance(module_data, dict) and "error" in module_data:
                    continue

                # Check if module has meaningful data
                module_findings = self._extract_module_findings(module_name, module_data)

                if module_findings:
                    elements.append(Paragraph(f"<b>{module_name}</b>", self.styles['Normal']))

                    # Create findings table
                    table_data = [["Finding", "Severity", "Details"]]
                    for f in module_findings[:15]:
                        table_data.append([
                            f['type'][:30],
                            f['severity'].upper(),
                            f['description'][:50],
                        ])

                    if len(table_data) > 1:
                        findings_table = Table(
                            table_data,
                            colWidths=[2 * inch, 1 * inch, 3 * inch]
                        )
                        findings_table.setStyle(TableStyle([
                            ('BACKGROUND', (0, 0), (-1, 0), self.colors["dark"]),
                            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                            ('FONTSIZE', (0, 0), (-1, -1), 8),
                            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
                            ('TOPPADDING', (0, 0), (-1, -1), 5),
                            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                        ]))
                        elements.append(findings_table)
                        elements.append(Spacer(1, 15))

            elements.append(Spacer(1, 20))

        return elements

    def _calculate_stats(self, results: Dict[str, Any]) -> dict:
        """Calculate summary statistics."""
        stats = {
            "total_targets": len(results),
            "modules_run": 0,
            "total_findings": 0,
            "high_severity": 0,
            "medium_severity": 0,
            "low_severity": 0,
        }

        module_names = set()

        for host, data in results.items():
            scans = data.get("scans", {})
            module_names.update(scans.keys())

            findings = self._extract_host_findings(scans)
            for f in findings:
                stats["total_findings"] += 1
                if f["severity"] == "high":
                    stats["high_severity"] += 1
                elif f["severity"] == "medium":
                    stats["medium_severity"] += 1
                else:
                    stats["low_severity"] += 1

        stats["modules_run"] = len(module_names)

        return stats

    def _extract_all_findings(self, results: Dict[str, Any]) -> List[dict]:
        """Extract all findings from all hosts."""
        all_findings = []

        for host, data in results.items():
            scans = data.get("scans", {})
            findings = self._extract_host_findings(scans)
            for f in findings:
                f["host"] = host
            all_findings.extend(findings)

        # Sort by severity
        severity_order = {"high": 0, "medium": 1, "low": 2}
        all_findings.sort(key=lambda x: severity_order.get(x["severity"], 3))

        return all_findings

    def _extract_host_findings(self, scans: Dict[str, Any]) -> List[dict]:
        """Extract findings from a host's scans."""
        findings = []

        for module_name, module_data in scans.items():
            module_findings = self._extract_module_findings(module_name, module_data)
            findings.extend(module_findings)

        return findings

    def _extract_module_findings(
        self, module_name: str, module_data: Dict[str, Any]
    ) -> List[dict]:
        """Extract findings from a specific module's data."""
        findings = []

        if not module_data or not isinstance(module_data, dict):
            return findings

        # Check for vulnerabilities list
        if "vulnerabilities" in module_data:
            for v in module_data["vulnerabilities"]:
                findings.append({
                    "module": module_name,
                    "type": v.get("type", "vulnerability"),
                    "severity": v.get("severity", "medium"),
                    "description": v.get("description", str(v)),
                })

        # Check for vulnerable flag
        elif module_data.get("vulnerable"):
            findings.append({
                "module": module_name,
                "type": "vulnerability",
                "severity": "high",
                "description": f"{module_name} detected vulnerability",
            })

        # Check for dangerous methods (HTTP Method Scanner)
        if "dangerous_methods" in module_data and module_data["dangerous_methods"]:
            methods = ", ".join(module_data["dangerous_methods"][:5])
            findings.append({
                "module": module_name,
                "type": "dangerous_methods",
                "severity": "medium",
                "description": f"Dangerous methods enabled: {methods}",
            })

        # Check for secrets (JS Secret Scanner)
        if "secrets" in module_data and module_data["secrets"]:
            for secret in module_data["secrets"][:5]:
                findings.append({
                    "module": module_name,
                    "type": "secret",
                    "severity": "high",
                    "description": f"Secret found: {secret.get('type', 'unknown')}",
                })

        # Check for security headers score
        if module_name == "Security Headers" and "score" in module_data:
            score = module_data["score"]
            if score < 50:
                findings.append({
                    "module": module_name,
                    "type": "low_score",
                    "severity": "medium",
                    "description": f"Security headers score: {score}/100",
                })

        return findings


def generate_pdf_report(results: Dict[str, Any], output_path: str, **kwargs):
    """Convenience function to generate PDF report."""
    generator = PDFReportGenerator()
    generator.generate(results, output_path, **kwargs)
